### PR TITLE
Adds support for file:// URLs

### PR DESCRIPTION
**Pull request by WolfgangD**

### CODE REVIEW

**Comment by Danielku15** [comment]
Closing this PR as urls should already be generated correctly

**Comment by WolfgangD** [comment]
They are parsed and handled correctly in the case of http(s) requests. However if alphatab is loaded in e.g. a webview component that is allowed to access local resources via the file protocol, it does not handle it correctly.

As it is only checking for urls starting with http it interprets the file url as relative path and fails to oad.

Additionally XHR requests loading a file url always have a status code of 0. This needs to be handled differently as well.

**Comment by Danielku15** [comment]
> Additionally XHR requests loading a file url always have a status code of 0. This needs to be handled differently as well.

The status code handling was added to the `ScoreLoader` in an earlier commit. 
https://github.com/CoderLine/alphaTab/blob/027634d3bfd640283c362d458696ed4077e25dc3/Source/AlphaTab.JavaScript/Importer/ScoreLoader.cs#L51

Also the file protocol handling was added as proposed in the PR: 
https://github.com/CoderLine/alphaTab/blob/027634d3bfd640283c362d458696ed4077e25dc3/Source/AlphaTab.JavaScript/Settings.cs#L1106
 
So I think all changes proposed in this PR are already part of the code. Let me know if you have the feeling that there is still a case open that is not handled correctly. 😉

**Comment by WolfgangD** [comment]
You're right. This should work and I could have closed the PR a long time ago ;).

**Pull request closed without merging**
