### PR TITLE
expose endTime and endTick

### PR DESCRIPTION
**Pull request by jacopomaroli**
### Issues

Fixes https://github.com/CoderLine/alphaTab/discussions/520

### Proposed changes
expose endTime and endTick

### Checklist
- [x] I consent that this change becomes part of alphaTab under it's current or any future open source license
- [x] Changes are implemented
- [ ] Existing builds tests pass
- [ ] New tests were added

## Further details
- [ ] This is a breaking change
- [x] This change will require update of the documentation/website

### CODE REVIEW

**Comment by jacopomaroli** [comment]
sorry, I could not run tests. I got a huge amount of
```
[1] 15 01 2021 17:44:18.575:INFO [http.server]: save visual error undefined
[1]     ✗ zeros-on-dive-whammys-off
[1] 	Difference between original and new image is too big: 472/8065 (5.85%) (undefined)
[1] 	Error
[1] 	    at <Jasmine>
[1] 	    at Function.<anonymous> (dist/lib.test/test/index.js:47860:43)
[1] 	    at <Jasmine>
[1] 	    at fulfilled (dist/lib.test/test/index.js:47653:62)
```
which seems to be unrelated so I stopped the process.

I did
```
nvm use lts/fermium
npm i
npm run test
```

**Comment by Danielku15** [comment]
Unfortunately this change will not deliver the desired results. I recommend you have a look first on how other values are passed back and forth within the synthesizer. You have to keep in mind that the actual synthesizer (the `AlphaSynth` instance) is living within the Web Worker and the `api.player` is just a component communicating with the worker. 

With this change `player.endTick` will be just undefined. The `IAlphaSynth` interface synchronizes the API on the `api.player` and the actual implementation in `AlphaSynth`.

**Comment by Danielku15** [comment]
@jacopomaroli I assume with my latest changes and discussion on #520 we can close this PR without merging?

**Comment by jacopomaroli** [comment]
yes, please procede closing this PR. Thanks!

**Pull request closed without merging**
