### PR TITLE
Add minor keys

### LINKED ISSUE #875: Minor Keys in AlphaTex
### Discussed in https://github.com/CoderLine/alphaTab/discussions/853

<div type='discussions-op-text'>

<sup>Originally posted by **jonaro00** May 15, 2022</sup>
## Proposed feature
AlphaTex currently allows defining major key signatures with `\ks G`. I propose also allowing minor keys by simply expanding the switch-cases in `AlphaTexImporter.parseKeySignature`.

What the syntax would be is up for discussion. My idea is to keep the default behavior for major keys, using `\ks Eminor` for minor, but also allowing `\ks Gmajor` for consistency.

The switch-case would then look like:
```
...
case 'g':
case 'gmajor':
case 'eminor':
    ...
```</div>

### PR DESCRIPTION
**Pull request by jonaro00**
### Issues
Fixes #875 

### Proposed changes
Adds the ability to specify minor keys in alphaTab. Major keys can also be explicitly stated.

### Checklist
- [x] I consent that this change becomes part of alphaTab under it's current or any future open source license
- [x] Changes are implemented
- [x] Existing builds tests pass
- [x] New tests were added

## Further details
- [ ] This is a breaking change
- [x] This change will require update of the documentation/website

### CODE REVIEW

**Review by Danielku15 — CHANGES_REQUESTED** [review]
Can you please add new unit tests for such kind of extensions?

**Comment by Danielku15** [comment]
@jonaro00 C#/Kotlin builds are broken by this change.

**Comment by jonaro00** [comment]
I think I managed to (poorly) implement toThrowError in C#. Kotlin is a bit trickier. Would appreciate help on that one.

**Comment by Danielku15** [comment]
Adapted the missing bits on the C# and Kotlin code to make them happy on your new `ToThrowError` usage. Thanks for the contribution 😁

**Pull request merged**
