### PR TITLE
Add Basic Color Test for RGB

### LINKED ISSUE #387: Unsupported format for color
Hi,

I am getting the error "unsupported format for color" when using version 1.0.1 of Alphatab.

Version used: 1.0.1
Platform used: JavaScript
Rendering engine used: SVG
Chrome Latest
Windows
Link to your project: Testing on Localhost, but will provide more information, and a test link if required.

Thank you

# Expected Results
Allow colors to be used, as per AlphaTab documentation.

# Observed Results
Alphatab not proceeding with loading of .gp file

# Steps to Reproduce (for bugs)

1. Error coming from Alphatab.JS, as per Title
2. Tried color from script and from data attribute
3.  Neither data attribute nor script work, project only works when color information is removed

# Possible Solution 
Remove color information, but then it is not possible to see anything, as background color precludes

### PR DESCRIPTION
**Pull request by kyledecot**
### Issues
Fixes #387 

### Proposed changes

Updates the `substring` logic in `Color.ts` to properly grab the RGB values. Without this change `numbers` ends up being an array w/ a single item in it with eventually causes the method to return `null`.

Screen Shot 2021-02-11 at 8 05 22 AM

### Checklist
- [x] I consent that this change becomes part of alphaTab under it's current or any future open source license
- [x] Changes are implemented
- [x] Existing builds tests pass
- [x] New tests were added

## Further details
- [ ] This is a breaking change
- [ ] This change will require update of the documentation/website

### CODE REVIEW

**Comment by kyledecot** [comment]
I might need some guidance here @Danielku15 – I'm not sure how these C# tests are generated / what I'm doing incorrectly.

**Comment by Danielku15** [comment]
Hi there. 
You can usually just run locally the build-csharp NPM script to generate the C# sources and compile them: https://alphatab.net/docs/contributing#npm-scripts

This way you get the same error locally and can inspect the C# code. You will notice that the test method is having a space which is not supported for C#: 

image

You will notice that all test names within alphaTab are following the kebab-case naming convention. This way you can fix the test.

**Comment by kyledecot** [comment]
Ah–okay. Thanks for the explanation. This should be fixed in https://github.com/CoderLine/alphaTab/pull/543/commits/bb1e13037c282f2c01b51424b5c14dadc5549d42

**Comment by Danielku15** [comment]
Thanks for the contribution. Merged the changes 👍

**Pull request merged**
